name: xpu

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  pull_request:
    paths:
      - ".github/workflows/xpu.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: write


jobs:
  unit-tests:
    runs-on: [self-hosted, intel]
    container:
      image: intel/intel-extension-for-pytorch:2.1.20-xpu
      ports:
        - 80
      options: --privileged -it --rm --device /dev/dri:/dev/dri -v /dev/dri/by-path:/dev/dri/by-path --ipc=host --cap-add=ALL
    
    steps:
    - uses: actions/checkout@v3
    - name: Check container state
      shell: bash
      run: |
        ldd --version
        python -c "import torch; print('torch:', torch.__version__, torch)"
        python -c "import torch; import intel_extension_for_pytorch; print('XPU available:', torch.xpu.is_available())"

    - name: Install transformers
      run: |
        git clone https://github.com/huggingface/transformers
        cd transformers
        git rev-parse --short HEAD
        pip install .

    - name: Install deepspeed
      run: |
        pip install py-cpuinfo
        pip install .[dev,autotuning]
          ds_report

    - name: Python environment
      run: |
        pip list

    - name: Unit tests
      run: |
        pip install pytest pytest-timeout tabulate
        cd tests/unit
        pytest --verbose accelerator/* --timeout=300 --timeout-method=thread
        pytest --verbose autotuning/* --timeout=300 --timeout-method=thread
        pytest --verbose checkpoint/test_moe_checkpoint.py checkpoint/test_reshape_checkpoint.py checkpoint/test_shared_weights.py --timeout=300 --timeout-method=thread
        pytest --verbose compression/* --timeout=300 --timeout-method=thread
        pytest --verbose elasticity/* --timeout=300 --timeout-method=thread
        pytest --verbose launcher/test_ds_arguments.py launcher/test_run.py launcher/test_user_args.py --timeout=300 --timeout-method=thread
        pytest --verbose moe/test_moe_tp.py/* --timeout=300 --timeout-method=thread
        pytest --verbose monitor/* --timeout=300 --timeout-method=thread
        pytest --verbose ops/adagrad/test_cpu_adagrad.py --timeout=300 --timeout-method=thread
        pytest --verbose runtime/test_autocast.py --timeout=300 --timeout-method=thread
        pytest --verbose runtime/test_data.py --timeout=300 --timeout-method=thread
        pytest --verbose runtime/test_ds_config_model.py --timeout=300 --timeout-method=thread
        pytest --verbose runtime/test_mup_optimizers.py --timeout=300 --timeout-method=thread
        pytest --verbose runtime/test_runtime_utils.py --timeout=300 --timeout-method=thread
        pytest --verbose runtime/activation_checkpointing/* --timeout=300 --timeout-method=thread
        pytest --verbose runtime/pipe/test_pipe_schedule.py --timeout=300 --timeout-method=thread
        pytest --verbose runtime/sparse_tensor/* --timeout=300 --timeout-method=thread
        pytest --verbose runtime/utils/* --timeout=300 --timeout-method=thread
        pytest --verbose runtime/zero/test_ignore_unused_parameters.py --timeout=300 --timeout-method=thread
        pytest --verbose runtime/zero/test_zero_config.py --timeout=300 --timeout-method=thread
        pytest --verbose runtime/zero/test_zero_dynamic_class.py --timeout=300 --timeout-method=thread
        pytest --verbose runtime/zero/test_zero_offloadpp.py --timeout=300 --timeout-method=thread
        pytest --verbose runtime/zero/test_zero_tiled.py --timeout=300 --timeout-method=thread
        pytest --verbose runtime/zero/test_zeropp.py --timeout=300 --timeout-method=thread
